"""Static academic park-network dataset used by ParkNova AI.

The map coordinates are conceptual positions for visualization. Travel times are
sample weights inherited from the uploaded AI lab notebook and are not live GPS
or traffic estimates.
"""

PARKS = [
    {
        "id": "saddar",
        "name": "Saddar",
        "type": "City Hub",
        "description": "Central starting hub connecting the western and coastal park clusters.",
        "x": 31,
        "y": 61,
        "accent": "cyan",
    },
    {
        "id": "jahangir-park",
        "name": "Jahangir Park",
        "type": "Urban Park",
        "description": "A historic green space positioned close to the central network.",
        "x": 57,
        "y": 51,
        "accent": "lime",
    },
    {
        "id": "bagh-ibne-qasim",
        "name": "Bagh Ibne Qasim",
        "type": "Coastal Park",
        "description": "A major recreational park that links multiple eastern routes.",
        "x": 48,
        "y": 39,
        "accent": "violet",
    },
    {
        "id": "shaheed-benazir-bhutto-park",
        "name": "Shaheed Benazir Bhutto Park",
        "type": "Waterfront Park",
        "description": "A waterfront destination and key gateway to Nisar Shaheed Park.",
        "x": 70,
        "y": 34,
        "accent": "rose",
    },
    {
        "id": "hill-park",
        "name": "Hill Park",
        "type": "Scenic Park",
        "description": "A scenic elevated park connecting the southern exploration cluster.",
        "x": 13,
        "y": 78,
        "accent": "amber",
    },
    {
        "id": "karachi-safari-park",
        "name": "Karachi Safari Park",
        "type": "Wildlife Park",
        "description": "A large recreational and wildlife destination in the western branch.",
        "x": 3,
        "y": 91,
        "accent": "emerald",
    },
    {
        "id": "aziz-bhatti-park",
        "name": "Aziz Bhatti Park",
        "type": "Lake Park",
        "description": "A peaceful lake-side node connected to Hill Park and Safari Park.",
        "x": 19,
        "y": 95,
        "accent": "blue",
    },
    {
        "id": "zamzama-park",
        "name": "Zamzama Park",
        "type": "Community Park",
        "description": "A community park on the northern route toward Hilal Park.",
        "x": 55,
        "y": 24,
        "accent": "pink",
    },
    {
        "id": "hilal-park",
        "name": "Hilal Park",
        "type": "Neighbourhood Park",
        "description": "A compact green space serving as an alternate approach to the goal.",
        "x": 65,
        "y": 11,
        "accent": "indigo",
    },
    {
        "id": "nisar-shaheed-park",
        "name": "Nisar Shaheed Park",
        "type": "Destination Park",
        "description": "A destination node reachable through two weighted park corridors.",
        "x": 82,
        "y": 16,
        "accent": "orange",
    },
]

GRAPH = {
    "Saddar": {"Jahangir Park": 5, "Hill Park": 10, "Bagh Ibne Qasim": 15},
    "Jahangir Park": {
        "Saddar": 5,
        "Bagh Ibne Qasim": 15,
        "Shaheed Benazir Bhutto Park": 18,
    },
    "Bagh Ibne Qasim": {
        "Saddar": 15,
        "Jahangir Park": 15,
        "Zamzama Park": 20,
        "Shaheed Benazir Bhutto Park": 18,
    },
    "Shaheed Benazir Bhutto Park": {
        "Jahangir Park": 18,
        "Bagh Ibne Qasim": 18,
        "Zamzama Park": 20,
        "Nisar Shaheed Park": 22,
    },
    "Hill Park": {"Saddar": 10, "Aziz Bhatti Park": 20, "Karachi Safari Park": 25},
    "Karachi Safari Park": {"Hill Park": 25, "Aziz Bhatti Park": 20},
    "Aziz Bhatti Park": {"Hill Park": 20, "Karachi Safari Park": 20},
    "Zamzama Park": {
        "Bagh Ibne Qasim": 20,
        "Shaheed Benazir Bhutto Park": 20,
        "Hilal Park": 23,
    },
    "Hilal Park": {"Zamzama Park": 23, "Nisar Shaheed Park": 22},
    "Nisar Shaheed Park": {"Shaheed Benazir Bhutto Park": 22, "Hilal Park": 22},
}

POSITIONS = {park["name"]: (float(park["x"]), float(park["y"])) for park in PARKS}

ALGORITHM_CATALOG = [
    {
        "id": "bfs",
        "name": "Breadth-First Search",
        "short": "BFS",
        "objective": "Fewest park-to-park transitions",
        "strength": "Complete and optimal for unweighted step count",
        "tradeoff": "Ignores travel-time weights",
        "complexity": "O(V + E)",
        "category": "Uninformed Search",
    },
    {
        "id": "dfs",
        "name": "Depth-First Search",
        "short": "DFS",
        "objective": "Deep exploratory route",
        "strength": "Low memory and useful for route exploration",
        "tradeoff": "Not guaranteed to return the shortest route",
        "complexity": "O(V + E)",
        "category": "Uninformed Search",
    },
    {
        "id": "ucs",
        "name": "Uniform Cost Search",
        "short": "UCS",
        "objective": "Minimum total travel time",
        "strength": "Optimal for non-negative edge costs",
        "tradeoff": "May explore many similarly priced paths",
        "complexity": "O((V + E) log V)",
        "category": "Cost-Based Search",
    },
    {
        "id": "iddfs",
        "name": "Iterative Deepening DFS",
        "short": "IDDFS",
        "objective": "Shallow route within a stop limit",
        "strength": "BFS-like completeness with DFS-like memory",
        "tradeoff": "Repeats earlier depth-limited searches",
        "complexity": "O(b^d)",
        "category": "Uninformed Search",
    },
    {
        "id": "astar",
        "name": "A* Search",
        "short": "A*",
        "objective": "Minimum travel time with informed guidance",
        "strength": "Optimal with the admissible geometric heuristic used here",
        "tradeoff": "Quality depends on the heuristic",
        "complexity": "Worst-case exponential; usually fewer expansions than UCS",
        "category": "Informed Search",
    },
    {
        "id": "hill_climbing",
        "name": "Hill Climbing",
        "short": "Hill",
        "objective": "Greedy progress toward the destination",
        "strength": "Fast and easy to understand",
        "tradeoff": "Can stop at a local optimum",
        "complexity": "O(b × d)",
        "category": "Local Search",
    },
    {
        "id": "csp",
        "name": "Constraint Route Solver",
        "short": "CSP",
        "objective": "Best simple route satisfying time and stop constraints",
        "strength": "Explicitly enforces user constraints",
        "tradeoff": "Backtracking can grow quickly on large graphs",
        "complexity": "Exponential in the worst case",
        "category": "Constraint Satisfaction",
    },
    {
        "id": "genetic",
        "name": "Genetic Algorithm",
        "short": "GA",
        "objective": "Evolve a valid low-time route",
        "strength": "Demonstrates population-based optimization",
        "tradeoff": "Stochastic and not guaranteed to find the global optimum",
        "complexity": "O(generations × population × path length)",
        "category": "Evolutionary Search",
    },
]
